version: '3.7'

volumes:
  peer1.manufacturer.auto.com:

networks:
  automobile:
    name: fabric_automobile

services:

  couchdb1:
    container_name: couchdb1
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5013:5013"
    networks:
      - automobile

  peer1.manufacturer.auto.com:
    container_name: peer1.manufacturer.auto.com
    image: hyperledger/fabric-peer:2.5.4
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_automobile
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.manufacturer.auto.com
      - CORE_PEER_ADDRESS=peer1.manufacturer.auto.com:5010
      - CORE_PEER_LISTENADDRESS=0.0.0.0:5010
      - CORE_PEER_CHAINCODEADDRESS=peer1.manufacturer.auto.com:5011
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:5011
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.manufacturer.auto.com:5010
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.manufacturer.auto.com:5010
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer1.manufacturer.auto.com:5012
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1manufacturer"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5013
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/manufacturer.auto.com/peers/peer1.manufacturer.auto.com:/etc/hyperledger/fabric
      - peer1.manufacturer.auto.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 5010:5010
      - 5012:5012
    depends_on:
      - couchdb1
    networks:
      - automobile